/* Replace this address before accepting production payments. */
const PAYMENT={recipient:'0xfFb22cd425bDcC2B06CB095C2F371a472E14fF04',chainId:'0x1',usdt:'0xdAC17F958D2ee523a2206206994597C13D831ec7',amount:1000000};
function bitsFor(text){const bytes=new TextEncoder().encode(text),data=[81,75,49,bytes.length>>8,bytes.length&255,...bytes];let hash=0;for(const byte of data)hash=(hash*31+byte)&65535;data.push(hash>>8,hash&255);return data.flatMap(byte=>Array.from({length:8},(_,shift)=>(byte>>(7-shift))&1))}
function makeMatrix(text){const bits=bitsFor(text);let side=Math.max(21,1+Math.floor(Math.sqrt(bits.length*1.35)));side+=(side-1)%2;if(bits.length>(side-8)**2)side+=2;const matrix=Array.from({length:side},()=>Array(side).fill(0)),reserved=new Set();const finder=(top,left)=>{for(let y=0;y<7;y++)for(let x=0;x<7;x++)matrix[top+y][left+x]=+(x===0||x===6||y===0||y===6||(x>=2&&x<=4&&y>=2&&y<=4))};for(const [top,left] of [[0,0],[0,side-7],[side-7,0]]){finder(top,left);for(let y=top-1;y<=top+7;y++)for(let x=left-1;x<=left+7;x++)if(x>=0&&y>=0&&x<side&&y<side)reserved.add(`${y},${x}`)}let index=0;for(let y=side-1;y>=0;y--){const columns=(side-1-y)%2===0?[...Array(side).keys()].reverse():[...Array(side).keys()];for(const x of columns)if(!reserved.has(`${y},${x}`))matrix[y][x]=(bits[index++]||0)^+((x+y)%3===0)}return matrix}
function render(text){const matrix=makeMatrix(text),zone=4,scale=10,size=matrix.length+zone*2,cells=matrix.flatMap((row,y)=>row.map((value,x)=>value?`<rect x="${(x+zone)*scale}" y="${(y+zone)*scale}" width="${scale}" height="${scale}"/>`:'' )).join('');svgMarkup=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size*scale} ${size*scale}" role="img" aria-label="Qarkod"><rect width="100%" height="100%" fill="white"/><g fill="black">${cells}</g></svg>`;preview.innerHTML=svgMarkup;document.querySelector('#matrix-size').textContent=`${matrix.length} × ${matrix.length}`}
function setStatus(message,kind=''){status.textContent=message;status.className=`status ${kind}`}
function encodeTransfer(recipient,amount){return `0xa9059cbb${recipient.slice(2).padStart(64,'0')}${amount.toString(16).padStart(64,'0')}`}
async function connectAndPay(){if(!window.ethereum){setStatus('Потрібен MetaMask або інший EVM-гаманець.','error');return}if(PAYMENT.recipient==='0x0000000000000000000000000000000000000000'){setStatus('Вкажіть адресу отримувача в app.js перед запуском.','error');return}try{const accounts=await window.ethereum.request({method:'eth_requestAccounts'});walletAddress=accounts[0];document.querySelector('#wallet-label').textContent=`${walletAddress.slice(0,6)}…${walletAddress.slice(-4)}`;const chain=await window.ethereum.request({method:'eth_chainId'});if(chain!==PAYMENT.chainId)await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:PAYMENT.chainId}]});setStatus('Підтвердіть переказ 1 USDT у гаманці…');const tx=await window.ethereum.request({method:'eth_sendTransaction',params:[{from:walletAddress,to:PAYMENT.usdt,data:encodeTransfer(PAYMENT.recipient,PAYMENT.amount)}]});setStatus('Очікуємо підтвердження транзакції…');let receipt;do{await new Promise(resolve=>setTimeout(resolve,1800));receipt=await window.ethereum.request({method:'eth_getTransactionReceipt',params:[tx]})}while(!receipt);if(receipt.status!=='0x1')throw new Error('Транзакція не підтверджена.');download.disabled=false;document.querySelector('#paid-note').textContent='Оплачено · готово до завантаження';setStatus('Оплату підтверджено. Qarkod готовий.','success')}catch(error){setStatus(error.code===4001?'Підпис скасовано у гаманці.':error.message||'Не вдалося виконати оплату.','error')}}
payload.addEventListener('input',()=>{document.querySelector('#character-count').textContent=`${payload.value.length} / 160`;if(payload.value)render(payload.value);else{preview.innerHTML=`<div class="empty-state">Ваш Qarkod<br>з'явиться тут</div>`;download.disabled=true}});document.querySelector('#clear-button').addEventListener('click',()=>{payload.value='';payload.dispatchEvent(new Event('input'));payload.focus()});walletButton.addEventListener('click',connectAndPay);download.addEventListener('click',()=>{const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([svgMarkup],{type:'image/svg+xml'}));link.download='qarkod.svg';link.click();URL.revokeObjectURL(link.href)});
